
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hospital_Mangment_Project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class appointment
{

    public int app_id { get; set; }

    public int? patient_id { get; set; }

    public int doc_id { get; set; }

    public System.DateTime app_date { get; set; }

}

}
